//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvtManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTISEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADVERTISEMENT()
        {
            this.DISCUSSIONs = new HashSet<DISCUSSION>();
        }
    
        public string Code { get; set; }
        public string Campaign_Code { get; set; }
        public decimal Cost { get; set; }
        public string Content_url { get; set; }
        public string Status { get; set; }
        public string Media_Code { get; set; }
    
        public virtual ADVT_STATUS_TYPE ADVT_STATUS_TYPE { get; set; }
        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual MEDIA_TYPE MEDIA_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUSSION> DISCUSSIONs { get; set; }
    }
}
