//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvtManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPAIGN()
        {
            this.ADVERTISEMENTs = new HashSet<ADVERTISEMENT>();
        }
    
        public string Code { get; set; }
        public long Request_id { get; set; }
        public string Department_Code { get; set; }
        public long Invoice_id { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        public virtual CAMPAIGN_STATUS_TYPE CAMPAIGN_STATUS_TYPE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual INVOICE INVOICE { get; set; }
        public virtual REQUEST REQUEST { get; set; }
    }
}
