//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvtManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string City_Code { get; set; }
        public string Industry_Code { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual INDUSTRY_TYPE INDUSTRY_TYPE { get; set; }
    }
}
